### ISSUE TITLE
Generate swagger consumes/produces for every action

### ISSUE THREAD

**Issue by ZandorZ** [goadesign/goa#1074]
I have an action that returns mimetype "application/vnd.myapp.user+json; type=collection" 
defined it in dsl by a collectionof MediaType("application/vnd.myapp.user+json")

Is there a way to define Consumes/Produces in every Action , not only on API ?
I tried it but it says: Invalid use of Produces in resource "user" action "list"

i need a generate swagger file that has defined the respective mimetype it actually produces
something like this:

```yaml
/users:
    get:
      description:
        Returns a list users
      consumes:
        - application/vnd.myapp.user+json
      produces:
        - application/vnd.myapp.user+json; type=collection
....
```

**Comment by raphael** [comment]
Hmm I don't see a reason not to always add the operation specific `Produces` field. Thanks for raising the issue!

**Comment by raphael** [comment]
I just merged code that sets the `Produces` field for each operation if it differs from the API level field. Can you validate and close the ticket if that does what you need?

**Comment by ZandorZ** [comment]
```golang

package design

import (
	. "github.com/goadesign/goa/design"
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("myapp", func() {
	Title("My App API")
	Description("My App API")
	Host("localhost:8080")
	BasePath("/api")
	Scheme("http")
	Origin("*", func() {
		Methods("GET", "PUT", "POST")
	})
})

//User
var _ = Resource("user", func() {
	Description("User resources")
	BasePath("/user")

	//list
	Action("list", func() {
		Routing(GET(""))
		Description("Return users list")
		Response(OK, CollectionOf(UserType))
		Response(BadRequest, ErrorMedia)
		Produces("application/json")
	})

....
```


I'm still getting the following error:
invalid use of Produces in resource "user" action "list"

**Comment by raphael** [comment]
The generator sets it by looking at the content or media type of the response, no need to specify it with `Produces`. Just re-generate with latest.

**Comment by raphael** [comment]
Also note that you can override the content type with `ContentType` in the [media type definition](https://goa.design/reference/goa/design/apidsl/#func-mediatype-a-name-apidsl-mediatype-a).

**Comment by ZandorZ** [comment]
Nice. Thank you
