### ISSUE TITLE
Goa 1.3 build broken by interface change to go.uuid

### ISSUE THREAD

**Issue by prowley** [goadesign/goa#1493]
This change https://github.com/satori/go.uuid/commit/0ef6afb2f6cdd6cdaeee3885a95099c63f18fc8c
to go.uuid breaks goa build.

**Comment by raphael** [comment]
Thanks, I just released `v1.3.1` which contains a fix for this issue.

**Comment by aweisser** [comment]
I still get an error using v1.3.1.
```
github.com\goadesign\goa\uuid\uuid.go:18:23: not enough arguments in call to uuid.Must
        have (uuid.UUID)
        want (uuid.UUID, error)
```
This occurs when using github.com/satori/go.uuid v1.2.0 as well as the current master branch.
Both branches contain a function ```func Must(u UUID, err error) UUID``` were as the next recent version v1.1.0 does not contain a function ```Must``` at all.

**Comment by aweisser** [comment]
Sorry. It does work with the master of github.com/satori/go.uuid.
Only the latest version v1.2.0 does not work.
But thats ok for now. 

Sorry for the interuption ;)

**Comment by v-o-v** [comment]
Is it fixed at 1.3.1?

**Comment by adam-hanna** [comment]
@v-o-v 

This is not a goa issue. As @Danlock pointed out in his linked issue, please change your Gopkg.toml:
```
[[constraint]]
    name = "github.com/satori/go.uuid"
    revision = "master"
````
