### ISSUE TITLE
goagen does not use vendor directory

### ISSUE THREAD

**Issue by jsimonetti** [goadesign/goa#444]
When vendoring a goa app the goagen tool does not pick up on the packages from the vendor directory.
It still expects package github/goadesign/goa to be in the GOPATH, while instead it is in the vendor path.

**Comment by raphael** [comment]
Fixed by #480

**Comment by peterochodo** [comment]
I am still facing this issue even though I am using goa release v1.2.0 which should have the fix cited in #480 above.
See below - note that from the error message, no effort was made to inspect the vendor folder:

~/workspace/yios/build/src/github.com/privnetworks/yios$ goagen -o modules/core app -d github.com/privnetworks/yios/modules/core/design
main.go:14:2: cannot find package "github.com/goadesign/goa/dslengine" in any of:
	/usr/local/go/src/github.com/goadesign/goa/dslengine (from $GOROOT)
	/home/peter/workspace/yios/build/src/github.com/goadesign/goa/dslengine (from $GOPATH)
main.go:11:2: cannot find package "github.com/goadesign/goa/goagen/gen_app" in any of:
	/usr/local/go/src/github.com/goadesign/goa/goagen/gen_app (from $GOROOT)
	/home/peter/workspace/yios/build/src/github.com/goadesign/goa/goagen/gen_app (from $GOPATH)

~/workspace/yios/build/src/github.com/privnetworks/yios$ ls vendor/github.com/goadesign/goa/dslengine
definitions.go  runner.go  validation.go
~/workspace/yios/build/src/github.com/privnetworks/yios$ echo $GOPATH
/home/peter/workspace/yios/build
